name: local_auth_device_credentials
description: Flutter plugin for Android and iOS device authentication sensors
  such as Fingerprint Reader, Touch ID, pin, pattern, or passcode.
homepage: https://github.com/yourfriendken/local_auth_device_credentials
version: 0.6.2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.localauth
        pluginClass: LocalAuthPlugin
      ios:
        pluginClass: FLTLocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  intl: '>=0.15.1 <0.17.0'
  platform: ^2.0.0
  flutter_plugin_android_lifecycle: ^1.0.2

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'
  flutter: '>=1.10.0 <2.0.0'
